import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { PrimaryLinkButton } from "~/component/PrimayLinkButton";

import { api } from "~/utils/api";

const Homepage: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  function HeroBanner() {
    return <section className="mt-24 mb-24 sm:mt-24 grid grid-cols-1 gap-12 px-8 sm:grid-cols-2">
      <div className="flex flex-col gap-4">
        <h1 className="text-6xl">Generate icon with click of a button</h1>
        <p className="text-2xl">
          USE AI to generate icons instead of paying a designer  and  waiting them to create for you
        </p>
        <PrimaryLinkButton className="self-start" href="/generate">Generate your icon</PrimaryLinkButton>
      </div>
      <Image
        src="/banner.png"
        alt="an image of multiple icons"
        width="400"
        height="300"
        className="order-first sm:-order-none"
      />

    </section>
  }

  return (
    <>
      <Head>
        <title>Icon Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center">
        <HeroBanner/>
      </main>
    </>
  );
};

export default Homepage;

